# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-openstack-provider'

$script = <<SCRIPT
# prep env and git clone
sudo apt-get update 
sudo apt-get install -y git vim 
git clone https://github.com/openstack-dev/devstack.git devstack
cd devstack
git checkout stable/kilo
#git reset aaae79b095fb4d4029077ed490adc61bf9e1eb46 
# between 47e68afd674fb387b99216f94eac3eb477a6e077(7.14) | 7aaaf9090145b3e84e1d9a3c90e12bd370f5f31f(7/11) and 54ee8a82a837eb2b28746c77e0259ec326ab15cc(7/15) identity-user page is fucked up
# identity-project page is fucked up all the way from e6f37b91e5cd5b0f70d2be1e75eb4f61adc1e16a 
# now trying d4da210ffb2a9f1274705ba04ec56337e7e1ea1c(7/23)
# aaae79b095fb4d4029077ed490adc61bf9e1eb46 now 
# worked for /etc/keystone/ssl
# but not horizon->identity pages
# d523a71514550a85657356ae7ffe4085800b42c6 still bad.. no identity/project page
#git reset --hard HEAD
# Make stack user, change ownership of devstack folder. 
# Build DevStack
sudo cp samples/local.conf .
sudo chown -R ubuntu *
sudo su ubuntu -c "./stack.sh"

# K2K federation 

SCRIPT

Vagrant.configure(2) do |config|
  # define instances in loop
  config.hostmanager.enabled = true
  #config.hostmanager.manage_host = true  # Annoyingly ask for pw

  config.vm.define "k2k-idp" do |devstack|
    devstack.ssh.username = 'ubuntu'
    # change to your own private key
    devstack.ssh.private_key_path = '~/.ssh/csail-mylu-key.pem'

    # define os instance
    devstack.vm.provider :openstack do |os|
      os.openstack_auth_url   = 'https://nimbus.csail.mit.edu:5001/v2.0/tokens'   
      os.username             = ENV['OS_USERNAME']
      os.password             = ENV['OS_PASSWORD']
      os.tenant_name          = ENV['OS_TENANT_NAME']
      os.flavor               = '4G-1C-32D'
      os.server_name          = "k2k-idp"
      os.image                = '4dc46de2-e7f8-457d-b3fb-eb082d81d87b'
      os.endpoint_type        = 'publicURL'
      # name of public key corresponding to ur private key on os project
      os.sync_method          = 'rsync'
      os.keypair_name         = 'csail-mylu-key' 
    end

    devstack.vm.provision "shell", inline: <<-SHELL
      cat /dev/null > /etc/hosts
    SHELL

    devstack.vm.hostname = "k2k-idp"
    devstack.vm.provision :hostmanager

    # shell command to update vm and install devstack
    devstack.vm.provision "shell", inline: $script

    devstack.vm.synced_folder "../auto-IdP", "/opt/stack/IdP"
    devstack.vm.synced_folder "../auto-SP", "/opt/stack/SP"
  end

  config.vm.define "k2k-sp" do |devstack|
    devstack.ssh.username = 'ubuntu'
    # change to your own private key
    devstack.ssh.private_key_path = '~/.ssh/csail-mylu-key.pem'

    # define os instance
    devstack.vm.provider :openstack do |os|
      os.openstack_auth_url   = 'https://nimbus.csail.mit.edu:5001/v2.0/tokens'   
      os.username             = ENV['OS_USERNAME']
      os.password             = ENV['OS_PASSWORD']
      os.tenant_name          = ENV['OS_TENANT_NAME']
      os.flavor               = '4G-1C-32D'
      os.server_name          = "k2k-sp"
      os.image                = '4dc46de2-e7f8-457d-b3fb-eb082d81d87b'
      os.endpoint_type        = 'publicURL'
      # name of public key corresponding to ur private key on os project
      os.sync_method          = 'rsync'
      os.keypair_name         = 'csail-mylu-key' 
    end

    devstack.vm.provision "shell", inline: <<-SHELL
      cat /dev/null > /etc/hosts
    SHELL

    devstack.vm.hostname = "k2k-sp"
    devstack.vm.provision :hostmanager

    # shell command to update vm and install devstack
    devstack.vm.provision "shell", inline: $script

    devstack.vm.synced_folder "../auto-SP", "/home/ubuntu/SP"
    devstack.vm.synced_folder "../auto-IdP", "/home/ubuntu/IdP"
  end
end
